### ISSUE TITLE
No initial conditions file available

### ISSUE THREAD

**Issue by Linkersem** [akpetty/NESOSIM#4]
I tried to run this program, but I ran into some problems. This problem seems to be due to lack of data. How can I solve this problem?
![image](https://user-images.githubusercontent.com/49711774/90585385-5102ae00-e207-11ea-9482-ee8b70cf28e3.png)

**Comment by akpetty** [comment]
Apologies for the slow reply. You can just run NESOSIM without initial conditions (change the IC flag). Does this work for you as a first step? 

We have more recently pushed new v1.1 code so hopefully this makes it easier to generate your own initial conditions or use the attached test forcings now.

**Comment by akpetty** [comment]
The v1.1 gridded initial conditions and forcing files used to generate the 1980-2021 output are now hosted on Zenodo: https://doi.org/10.5281/zenodo.6338558. Please do let me know if you have any issues using these.
